name: weather_chatbot_new
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Contoh batasan SDK

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.0.0
  csv: ^5.0.0
  lottie: ^3.3.0
  shared_preferences: ^2.3.2
  flutter_launcher_icons: ^0.14.2
  intl: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/animations/
    - assets/images/
flutter_launcher_icons:
  android: true # Aktifkan pembuatan ikon Android
  ios: true # Aktifkan pembuatan ikon iOS
  image_path: "assets/icons/icon.png"
